### ISSUE TITLE
Alternative array access with [ ]

### ISSUE THREAD

**Issue by Libavius** [j3-fortran/fortran_proposals#114]
Allow for alternative array acess:
```
my_array[3]
```
instead of
```
my_array(3)
```
in order to distinguis between array access and function call.

**Comment by cmacmackin** [comment]
This would conflict with coarray indexing. Also, frankly, the last thing Fortran needs is more ways to do the same thing. It is already full of those and it makes the source a devil to parse and analyse.

**Comment by Libavius** [comment]
> This would conflict with coarray indexing. Also, frankly, the last thing Fortran needs is more ways to do the same thing. It is already full of those and it makes the source a devil to parse and analyse.

I never worked with coarrays, so I did not know this. Thanks for the clarification =)

**Comment by certik** [comment]
Yes, the a[3] syntax is already taken, so this would be very hard to do.
