### ISSUE TITLE
Conditional Expressions

### ISSUE THREAD

**Issue by certik** [j3-fortran/fortran_proposals#12]
Initial recent paper: https://j3-fortran.org/doc/year/18/18-274.txt (there is a long history of trying to get something like this standardized).

# Motivation

Citing from the paper:
People have wanted to write things like
```fortran
  IF (I<N .AND. A(I)==0) ...
```
for decades.  So far, we have fobbed them off and they have to write
```fortran
  IF (I<N) THEN
    IF (A(I)) ...
  END IF
```
which is not just verbose but less convenient when wishing to test a series
of conditions.

Similarly, writing
```fortran
  IF (PRESENT(D)) THEN
    CALL SUB(A,B,C,D)
  ELSE IF (X<1) THEN
    CALL SUB(A,B,C,EPSILON(X))
  ELSE
    CALL SUB(A,B,C,SPACING(X))
  END IF
```
is verbose but usable when only one argument is conditional, but rapidly
degenerates when there are several arguments requiring similar handling.

**Comment by certik** [comment]
It seems the proposed syntax in `18-274` for the last example would be:
```fortran
SUB(A,B,C,IF (PRESENT(D)) THEN D ELSE IF (X<1) THEN EPSILON(X) ELSE SPACING(X))
```

**Comment by victorsndvg** [comment]
Dear @certik ,

I agree that short-circuit conditional evaluation could be an interesting feature.

On the other hand, Fortran provides the [merge](https://gnu.huihoo.org/gcc/gcc-7.1.0/gfortran/MERGE.html) instrinsic that, I think, it covers the your example (quoted) below (ternary operator):
> ```fortran-modern
> CALL SUB(A,B,C,IF (PRESENT(D)) THEN (D) ELSE IF (X<1) THEN (EPSILON(X)) ELSE (SPACING(X)) END IF)
> ```

**Comment by zbeekman** [comment]
Short circuit conditionals might alleviate a lot of segmentation faults; I know this would have saved my hide a few times.

**Comment by certik** [comment]
@victorsndvg, @zbeekman thanks for the feedback. Note that this particular proposal began long before my time at the committee and I don't feel very strongly either way on this particular one. I am watching what the committee works on and discusses and I am trying to create issues here for each proposal, to track it.

**Comment by zbeekman** [comment]
Yes weighing in here with community feedback! Thanks for doing this @certik! I'd love to see J3 put more proceedings/documents/etc. on GitHub or GitLab.

**Comment by zjibben** [comment]
The difference with merge is 1) merge may evaluate all options regardless of the logical expression and 2) merge returns values, not variables. So `merge(a, b, present(a))` is compiler-dependent; it might fail if `a` is not present, because `a`s value could be accessed. By making the variable, not the value, the result of the expression, you can use this as an `intent(out)` argument. E.g., `call get_x(if (l) then (a) else (b) endif)` works to assign to either `a` or `b`.

Though short-circuiting appeared in the initial paper, it isn't really being pursued here. Which is unfortunate; I'm much more interested in short-circuiting than conditional expressions.

**Comment by certik** [comment]
The main feedback from the committee seems to be that the conditional expression proposal above does not make things much simpler or clearer, and the new syntax does not seem appealing. The alternative is to short-circuit logical expressions, so this:
```fortran
  IF (I<N .AND. A(I)==0) ...
```
could be written, e.g., as:
```fortran
  IF (I<N .ANDTHEN. A(I)==0) ...
```
That way the old `.and.` works as before, and `.andthen.` short-circuits the conditional. (There is also an option to make `.andthen.` just `.and.`, the argument pro is that it does not introduce any new syntax, but one argument against it is that it would change the current freedom for compilers to re-arrange logical expressions -- either way this can be discussed elsewhere.)
