### ISSUE TITLE
Allow the default constructors of derived-types to initialize private fields

### ISSUE THREAD

**Issue by difference-scheme** [j3-fortran/fortran_proposals#193]
One of the most annoying restrictions in the language is that Fortran's default constructors for derived types do not always allow one to initialize the private fields of these types. That is, if one has a derived type like the following,
```
type :: AClass
   private
   class(BClass), allocatable :: b
contains
   procedure :: some_method_of_aclass_that_uses_b
end type AClass

```
as it happens extremely frequently in object-oriented programming, then the language will typically forbid passing some instance of `BClass` to the default constructor that generates objects of type `AClass`, e.g. the following, perfectly reasonable code, would not be allowed
```
subroutine some_other_procedure(b)
   class(BClass), intent(in) :: b
      
   ! local declaration of an object of AClass
   class(AClass), allocatable :: a

   ! initialization using default constructor of AClass
   a = AClass(b)
end subroutine some_other_procedure

```
if `some_other_procedure` is not a part of the module in which `AClass` is declared. One has to either

- remove the `private` access specifier from the  `AClass` derived type, in order to be able to use the default constructor, which is unacceptable in object-oriented programming, since the latter relies critically on implementation hiding, or
- write a user-defined constructor (despite the obvious triviality of the above example), with all the hoop-jumping and verbosity that this involves in Fortran, like overloading the name of the derived type, etc.
- put all these declarations into the same module, which is rarely possible in practice.

The net result presently is that the object-oriented programmer has to write user-defined constructors for _all but the very simplest_ of his classes (namely those that contain _no_ fields at all)!

Allowing the initialization of private components by Fortran's default constructors, even if these are called from external scoping units, would go a long way in removing some of the drudgery that the language presently imposes on object-oriented programmers.

**Comment by FortranFan** [comment]
You will know Fortran is not, and likely never will be, a fully class-based, object-oriented language the way are some other programming languages e.g., Java.  Limitations with adopting OO approaches in Fortran are going to remain because of how the language evolves with ISO IEC standards process, committee consensus where language bloat and resource constraints all around, particularly with compiler implementations, are a matter of major concern.

Under the circumstances, some verbosity with custom `initialization` procedures is what programmers have to author in order to workaround such aspects.  What really are the issues - beyond verbosity - with this such workarounds is the question.  You may find the point - `oh, it's way too verbose even for trivial situations` - to be insufficient to convince a committee.

**Comment by difference-scheme** [comment]
To answer the question "what really are the issues - beyond verbosity - with such workarounds":

The language is inconsistent. 

It provides a single feature (the derived type) to support both the notions of "structures", and "classes" (as they are called in other languages) in a unified manner. Hence, the programmer can rightly expect that the language's main facility to construct such derived types (the default constructor) will work equally well for both these application cases, i.e. structures _and_ classes.

Well, it doesn't.

It works for structures, but not (in general) for classes (where implementation hiding is of paramount importance). I consider this a design flaw in the language, a "wart" as such things have been called in the past. It makes the language inconsistent, and hence nonintuitive to use, especially for newbies.

Good, consistent design would provide a _single_ default means to construct instances of both cases, consistent with the language's aim of offering only a single feature to support both structures and classes. It is ok if the language wishes to offer more functionality (like, e.g., user-defined constructors) than the bare minimum required by consistency, but the bare minimum (the default constructor) must work!

So, my proposal is essentially one of "wart removal", as it has been done repeatedly in the past.

**Comment by klausler** [comment]
What specific change are you proposing -- simply ignoring accessibility of components in a structure constructor?

**Comment by everythingfunctional** [comment]
@difference-scheme , I understand that most of the time one wants a public constructor whose arguments are simply the components of my type, but if we make that public by default then I don't see how I can prevent users of some module from using and relying on it in cases where I don't want that to be the case.

**Comment by difference-scheme** [comment]
@klausler My aim so far was simply to point out the problem, not necessarily to show a specific way to overcome it. 

I could imagine, that simply ignoring the accessibility of components in a structure constructor might lead to a lot of trouble. This needs to be thought through by someone with much more insight into how Fortran handles access attributes than myself.

**Comment by difference-scheme** [comment]
@everythingfunctional I am not sure I understood your concern.

What does "that" refer to in your sentence "but if we make that public"? The constructor/underlying derived type itself?
The problem I pointed out is one related to access attributes of derived type _components_, not of derived types themselves!

**Comment by everythingfunctional** [comment]
In Fortran, the derived type name and its default constructor have the same name. However, the default constructor is not made public along with the type if any of its components (without default initializers) are private. If you're suggesting that the default constructor should be made public even if its components are private, that can cause an issue, because I no longer have a way of making the default constructor private if the type is public. There are times where that is exactly what I want to do. I want to have complete control over how users of my type are allowed to construct instances of it, so that I can prevent them from being able to construct an object with inconsistent internal state.

**Comment by FortranFan** [comment]
@difference-scheme wrote Jan 21, 2021 3:51 PM EST:

> .. It works for structures, but not (in general) for classes ..

Per the Fortran standard, there is **no** such distinction.  Fortran language has intrinsic types and derived types. 

The issue here is with PRIVATE components for a derived type: programmers have 2 options:
1. When applicable, employ `default initialization` of derived type components e.g.,
```Fortran
type :: BClass
   integer :: n = 0
end type
```
2. When `default initialization` is inapplicable such as with components of allocatable attribute, employ a generic interface with the same name as the derived type e.g.,
```Fortran
interface BClass
   module procedure Construct_BClass1
   module procedure Construct_BClass2
   ..
end interface

So then the issue with this is some programmer will find it too "verbose" having to code one or more such functions (Construct_BClass1, etc.).

My point is if the verbosity and the added work on the designer of the derived type (BClass) above is the issue, this will not make priority.

Hence my question above as to what really are the issues - beyond verbosity - with going with the options 1 and/or 2 I list here.

**Comment by difference-scheme** [comment]
@everythingfunctional "However, the default constructor is not made public along with the type if any of its components (without default initializers) are private."

Could you point me to the Section number in the document of the Fortran 2018 standard where this is stated/discussed? Thanks.

**Comment by everythingfunctional** [comment]
Sure. In Section 7.5.10 Construction of derived-type values, there are two constraints when taken together imply the way I phrased it.

C799 (R756) A component-spec shall be provided for a nonallocatable component unless it has default initialization 

C7102 (R756) The type name and all components of the type for which a component-spec appears shall be accessible in the scoping unit containing the structure constructor.

**Comment by FortranFan** [comment]
@everythingfunctional wrote Jan 21, 2021 6:44 PM EST:

> .. Section 7.5.10 Construction of derived-type values, there are two constraints when taken together imply the way I phrased it. ..

@everythingfunctional ,

Please note the standard isn't prohibitive the way your statement would come across given what those constraints do not cover when it comes to PRIVATE derived type components with ALLOCATABLE attribute and those with default initialization.

```Fortran
module m
   type :: t
      private
      integer, public :: n = 0
      real :: x = 99.0
      character(len=:), allocatable :: s
   end type
contains
   subroutine print_t( a )
      type(t) , intent(in) :: a
      print *, "a%n: ", a%n
      print *, "a%x: ", a%x
      print *, "Is a%s allocated? ", allocated(a%s)
   end subroutine 
end module
   use m
   type(t) :: foo
   foo = t( n=42 )
   call print_t( foo )
end 
```
From what I can deduce, this example conforms and a couple of processors agree.
> C:\Temp>ifort /standard-semantics /warn:all /stand:f18 c.f90
> Intel(R) Fortran Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.1.2 Build 20201208_000000
> Copyright (C) 1985-2020 Intel Corporation.  All rights reserved.
> 
> Microsoft (R) Incremental Linker Version 14.26.28806.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> -out:c.exe
> -subsystem:console
> c.obj
> 
> C:\Temp>c.exe
>  a%n:  42
>  a%x:  99.00000
>  Is a%s allocated?  F
> 
> C:\Temp>gfortran -Wall -std=f2018 c.f90 -o gcc-c.exe
> 
> C:\Temp>gcc-c.exe
>  a%n:           42
>  a%x:    99.0000000
>  Is a%s allocated?  F
> 
> C:\Temp>

**Comment by FortranFan** [comment]
As I commented upthread, an author of a derived type can implement one or more functions to add to the generic interface in a manner that does satisfies the rules toward generic resolution in the standard.  The consumer can then "construct" using the default structure constructor or the one added to the interface depending on the situation.  See below.

```Fortran
module m
   type :: t
      private
      integer, public :: n = 0
      real :: x = 99.0
      character(len=:), allocatable :: s
   end type
   interface t
      module procedure construct_t_1
   end interface 
contains
   subroutine print_t( a )
      type(t) , intent(in) :: a
      print *, "a%n: ", a%n
      print *, "a%x: ", a%x
      print *, "Is a%s allocated? ", allocated(a%s)
      if ( allocated(a%s) ) then
         print *, "a%s: ", a%s
      end if    
   end subroutine
   function construct_t_1( s ) result(new_t)
      ! Argument list
      character(len=*), intent(in) :: s
      ! Function result
      type(t) :: new_t
      new_t%s = s
   end function 
end module
   use m
   type(t) :: foo
   type(t) :: bar
   foo = t( n=42 )
   call print_t( foo )
   bar = t( s="Hello" )
   call print_t( bar )
end 
```
> C:\Temp>ifort /standard-semantics /warn:all /stand:f18 c.f90
> Intel(R) Fortran Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.1.2 Build 20201208_000000
> Copyright (C) 1985-2020 Intel Corporation.  All rights reserved.
> 
> Microsoft (R) Incremental Linker Version 14.26.28806.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> -out:c.exe
> -subsystem:console
> c.obj
> 
> C:\Temp>c.exe
>  a%n:  42
>  a%x:  99.00000
>  Is a%s allocated?  F
>  a%n:  0
>  a%x:  99.00000
>  Is a%s allocated?  T
>  a%s: Hello
> 
> C:\Temp>gfortran -Wall -std=f2018 c.f90 -o gcc-c.exe
> 
> C:\Temp>gcc-c.exe
>  a%n:           42
>  a%x:    99.0000000
>  Is a%s allocated?  F
>  a%n:            0
>  a%x:    99.0000000
>  Is a%s allocated?  T
>  a%s: Hello
> 
> C:\Temp>

**Comment by FortranFan** [comment]
As worded, the original post and the subsequent comments by OP come across as the case where an author (or author(s)) is unwilling to do the bit of extra work to extend the generic interface as I show in my previous comment on account of verbosity or whatever.

Given where things are with Fortran with all the resource constraints, especially the committee time, this will then be a low priority.  Hence my suggestion to provide more of a justification with more detailed examples.

**Comment by everythingfunctional** [comment]
@FortranFan , your example does not have any private components without default initializers, hence it does not contradict my statement or the constraints in the standard.

**Comment by everythingfunctional** [comment]
@FortranFan , oh, I see. You just meant if someone skipped my parenthetical. Yes, my statement is not quite correct without that parenthetical.

**Comment by difference-scheme** [comment]
@everythingfunctional 
> However, the default constructor is not made public along with the type if any of its components (without default initializers) are private.

> Sure. In Section 7.5.10 Construction of derived-type values, there are two constraints when taken together imply the way I phrased it.
> 
> C799 (R756) A component-spec shall be provided for a nonallocatable component unless it has default initialization
> 
> C7102 (R756) The type name and all components of the type for which a component-spec appears shall be accessible in the scoping unit containing the structure constructor.

Just to wrap this up. 

Your first statement, that I quoted above, is wrong. In particular, it does not follow in any way from the two constraints of the Fortran standard cited in your second statement.

There is an implicit assumption in your whole argument/concern, namely that the access specifiers of derived type components (appearing in a component-spec) affect in some way the accessibility of the type itself, and accordingly its structure constructor. This is wrong.

Derived types as a whole have _their own_ access specifiers, that are independent of the access specifiers of their components. The standard is very clear about this. Section "7.5.2.2. Accessibility" states (I'm quoting from the draft for ballot of the 2018 standard, so the numbering might not be the final one):

"The accessibility of a type name is determined as specified in 8.5.2. [i.e. by its own access specifier].The accessibility of a type name does not affect, and is not affected by, the accessibility of its components and type-bound procedures."

The comment in brackets in the above quote is mine. So, in summary, Section 7.5.2.2. of the standard invalidates your entire concern.

**Comment by difference-scheme** [comment]
@klausler After some thought, and after I had a look into the standard, here is the specific change that I propose. The aforementioned constraint C7102:

> C7102 (R756) The type name and all components of the type for which a component-spec appears shall be accessible in the scoping unit containing the structure constructor.

should be relaxed/changed to:

"The type name shall be accessible in the scoping unit calling the structure constructor."

This essentially follows your suggestion of ignoring the accessibilty of components _during the initialization process_. 

I have come to the conclusion that it doesn't make any sense to honour the privacy/accessibility of something that doesn't exist (in memory, because it hasn't been initialized) yet. Notice, that I have also changed the word "containing" (which I find ambiguous) into "calling" (but this is a minor thing).

I believe this change should be backwards compatible, as it simply relaxes a former, more stringent, constraint.

I'd be grateful for any feedback that you might have. Kudos for your original suggestion!

**Comment by klausler** [comment]
I don't think this is a good idea.  If a component is private, the designer of the derived type has chosen to hide that part of the implementation from the interface.

**Comment by difference-scheme** [comment]
@klausler Yes, but private or not, he (the designer) still needs to initialize it. 

The change would simply bring the default structure constructor on an equal footing with a user-defined constructor. The latter _is_ allowed to effect such initialization, then why should we _deny_ the same right to the structure constructor? It is as much associated to the derived type as a user constructor is!

**Comment by klausler** [comment]
The interface to a user-defined constructor (a generic interface with the same name as the derived type) is under control of the designer of the type, who can hide or expose aspects of the implementation as they see fit.  Allowing private components to appear in a structure constructor would expose parts of the implementation that the type's designer has chosen to hide.

When components are inaccessible, the implementation is free to remove them, change their types, rename them, and extend them without worrying about needing clients to make concomitant changes, so long as the published interface remains unchanged.  Ignoring accessibility restrictions for structure constructors would wreck that guarantee.

**Comment by difference-scheme** [comment]
@klausler I see your point. Thanks for the feedback.

**Comment by difference-scheme** [comment]
From @klausler's last comment, I have to conclude that (due to the very way the language is designed) it is impossible to avoid the aforementioned asymmetry between default/structure constructors and user-defined constructors, without breaking the principle of information hiding in some form. I will therefore close this issue.

**Comment by FortranFan** [comment]
@difference-scheme wrote Jan. 22, 2021 7:40 PM EST:

> .. aforementioned asymmetry between default/structure constructors and user-defined constructors..

This point is wrong, there is no such asymmetry.
