### ISSUE TITLE
Treat unused variable as error?

### ISSUE THREAD

**Issue by Beliavsky** [j3-fortran/fortran_proposals#205]
Should the declaration of a variable or parameter that is never referenced be treated as an error? Compilers would still be able to compile code with unused variables, but codes compiled with a standard conformance option would not be allowed to have unused variables or parameters. Variables and parameter that are public in a module but not used in it would be allowed, but never-referenced private variables and parameters would be flagged.

This suggestion is in the spirit of making IMPLICIT NONE the default -- break bad code to encourage modernization. Some compilers already have options to warn about unused variables, and to turn such warnings into errors. The question is whether compilers should be required to have this capability.

**Comment by klausler** [comment]
Define "unused", please.  Is `x` unused in `0 * purefunc(x)`?  Or `MERGE(0,x,.true.)`?  Or `DO j=1,0; y = x; END DO`?

**Comment by Beliavsky** [comment]
Maybe I should use the term "never referenced". If the code would still compile if the variable were never declared and IMPLICIT NONE was in place, the variable can be considered never referenced (unless it is a public module variable).

**Comment by nncarlson** [comment]
Conceivably for a local variable, but absolutely not in general. Consider a type bound procedure with a dummy argument that is not referenced, but whose interface is fixed because it is defined by a parent class.  Such a rule would require the procedure to do something artificial with the argument just to avoid an error.  A warning is perfectly adequate.

**Comment by Beliavsky** [comment]
I was not sure this idea was good when I proposed it, and no one else seems strongly in favor of it, so I am closing this issue.

**Comment by certik** [comment]
Probably not as a language feature, but what Rust does is that it warns you if a variable is unused, and you can prefix the variable with an underscore to silence the warning. So something similar can be implemented in Fortran compilers.
