### ISSUE TITLE
Add INTRINSIC module nature to the index.

### ISSUE THREAD

**Issue by jme52** [j3-fortran/fortran_proposals#215]
This is a proposal of a minor edition to the index, which I am aware is nonnormative material (but very useful).

All references are to N2184, although the same issue exists in the current standard.

INTRINSIC is an attribute, a statement, and a *module-nature* (see R1410).

At the moment, both the INTRINSIC attribute and the INTRINSIC statement have entries in the index, but the INTRINSIC *module-nature* does not appear in the index at all.

The only other *module-nature* allowed, "NON_INTRINSIC", has an entry in the index, pointing to the page that contains R1410.  The same is true for "*module-nature* (R1410)".

I think that, for consistency and completeness, there should be an "INTRINSIC module nature" entry in the index, pointing to R1410 (with the page number in boldface).

**Comment by sblionel** [comment]
To close this out - email sent to @jme52  back in July:

Hi José,

I had a discussion on this with Malcolm Cohen, the standard's editor. He is not in favor of indexing "intrinsic module" as it appears almost 500 places in the standard. He proposed instead that he would index:
    INTRINSIC module nature
    NON_INTRINSIC module nature

which I think would accomplish what you want.
