### ISSUE TITLE
Proposal for default value of optional function/subroutine arguments

### ISSUE THREAD

**Issue by nebulaekg** [j3-fortran/fortran_proposals#41]
Fortran cannot set default value in function/subroutine definition for optional arguments. This is an apparent inconvenience if there are multiple optional arguments, compared with C/C++. In such case, using if(present()) can become rather cumbersome. I'd hope that future fortran has such functionality.

**Comment by certik** [comment]
@nebulaekg thanks for reporting this. Isn't this a duplicate of #22?

**Comment by nebulaekg** [comment]
> @nebulaekg thanks for reporting this. Isn't this a duplicate of #22?

Hi Ondrej, Yes I missed it. Sorry about this.

**Comment by certik** [comment]
@nebulaekg no worries! Go ahead and upvote #22 or comment there with improvements. I am going to close this one.
