### ISSUE TITLE
Issue Labels

### ISSUE THREAD

**Issue by zjibben** [j3-fortran/fortran_proposals#7]
Should we have labels for stages of various issues? The readme suggests we'll be tracking proposals through to final standardization, or rejection. Labels along the lines of "unsubmitted", "accepted", "rejected", "under consideration", "on hold", and maybe "in progress" would help organize this. And perhaps a "meta" label for issues related to this repo. I imagine "accepted" and "rejected" labels would only be used for closed issues.

**Comment by certik** [comment]
I think that's a great idea. Go ahead and create such labels.

**Comment by zjibben** [comment]
I added labels and assigned them to existing issues, feel free to modify as needed.

**Comment by pdebuyl** [comment]
What does "unsubmitted" mean?

**Comment by certik** [comment]
@pdebuyl I just added a remark for the label ("Has not been submitted to the committee yet").

**Comment by zbeekman** [comment]
You might want to pin this issue; or a similar one discussing labeling.

**Comment by milancurcic** [comment]
Now that we have the meta label, we don't need [META] in meta issue titles, correct? I did some tidying up with meta labels, then stumbled upon this. I'll revert if you disagree.

**Comment by certik** [comment]
That's fine with me, you can remove the [META] label.

**Comment by Libavius** [comment]
What about adding labels for different types of proposals (i.e. 'syntactic sugar', 'C interoperability', 'coding convention', 'efficiency improvement', 'new feature', 'enhanced feature'...)? In a way, this has already been done with the 'meta' label.

**Comment by certik** [comment]
We have issue labels now, so I am going to close this issue.
